#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan  7 13:50:19 2019

@author: baran
"""

# Modify phase encoding and write .json data 
def copy_json(dwi,referenceJson,basenameOut,peDir,numberOfVolumes):
    
    import json
    import numpy as np
    import sys

    fid = open(referenceJson);
    dwiInfo=json.load(fid);
    fid.close();
    
    report = open((basenameOut + '.json'),'w');    
    report.write('{\n');
    report.write('"generated by": "dwiprep -> parseInput -> run_parseInput"');
    report.write(',\n"input": "' + dwi + '"');    
    report.write(',\n"output": "' + basenameOut + '"');

    report.write(',\n"dcmmeta_shape": '              + str(dwiInfo['dcmmeta_shape']));

    if numberOfVolumes :
        report.write(',\n"number of volumes": '             + str(numberOfVolumes));
    else:
        report.write(',\n"number of volumes": '             + str(int(dwiInfo['number of volumes'])));

        
    report.write(',\n"PartialFourier": '                + str(float(dwiInfo['PartialFourier'])));
#    report.write(',\n"ImageOrientationPatientDICOM": '  + str(dwiInfo['ImageOrientationPatientDICOM']));
    report.write(',\n"TotalReadoutTime": '              + str(float(dwiInfo['TotalReadoutTime'])));
    
    report.write(',\n"MultibandAccelerationFactor": '   + str(dwiInfo['MultibandAccelerationFactor']));
    
    try:
        sliceTimings = dwiInfo['global']['slices']['CsaImage.TimeAfterStart'][0:dwiInfo['dcmmeta_shape'][2]];
        report.write(',\n"global":{');
        report.write('\n"slices":{');
        report.write('\n"CsaImage.TimeAfterStart": '+str(sliceTimings));
        report.write('\n}');
        report.write('\n}');
    except:
        sys.stdout.write('');
    
    
    if peDir :
        report.write(',\n"PhaseEncodingDirection": "'    + peDir + '"');
    else :
        report.write(',\n"PhaseEncodingDirection": "'     + dwiInfo['PhaseEncodingDirection'] + '"');
        
    report.write(',\n"result": "SUCCESS"');
    report.write('\n}');
    report.close();

# Merge all
def run_mergePhaseEncodedDwi(RL_dwis,LR_dwis,PA_dwis,AP_dwis,IS_dwis,SI_dwis,outputPath):
    
    from aux import nifti_concatenateDwi;
    
    dwis = [];
    
    (dwi,numberOfVolumes) = nifti_concatenateDwi((outputPath + '/RL.nii.gz'),RL_dwis);
    if dwi : 
        dwis.append(dwi);
        copy_json(RL_dwis[0],(RL_dwis[0][0:-7] + '.json'), (outputPath + '/RL'),[],numberOfVolumes);
        
    (dwi,numberOfVolumes) = nifti_concatenateDwi((outputPath + '/LR.nii.gz'),LR_dwis);
    if dwi :
        dwis.append(dwi);
        copy_json(LR_dwis[0],(LR_dwis[0][0:-7] + '.json'), (outputPath + '/LR'),[],numberOfVolumes);

    (dwi,numberOfVolumes) = nifti_concatenateDwi((outputPath + '/AP.nii.gz'),AP_dwis);
    if dwi :
        dwis.append(dwi);
        copy_json(AP_dwis[0],(AP_dwis[0][0:-7] + '.json'), (outputPath + '/AP'),[],numberOfVolumes);

    (dwi,numberOfVolumes) = nifti_concatenateDwi((outputPath + '/PA.nii.gz'),PA_dwis);
    if dwi :
        dwis.append(dwi);
        copy_json(PA_dwis[0],(PA_dwis[0][0:-7] + '.json'), (outputPath + '/PA'),[],numberOfVolumes);

    (dwi,numberOfVolumes) = nifti_concatenateDwi((outputPath + '/SI.nii.gz'),SI_dwis);
    if dwi :
        dwis.append(dwi);
        copy_json(SI_dwis[0],(SI_dwis[0][0:-7] + '.json'), (outputPath + '/SI'),[],numberOfVolumes);

    (dwi,numberOfVolumes) = nifti_concatenateDwi((outputPath + '/IS.nii.gz'),IS_dwis);
    if dwi :
        dwis.append(dwi);
        copy_json(IS_dwis[0],(IS_dwis[0][0:-7] + '.json'), (outputPath + '/IS'),[],numberOfVolumes);
        
    return dwis;
    

# Parse input
def run_parseInput(dwi,basenameOut):
    
    import os
    import sys
    import nibabel as nib
    import numpy as np
    import json
    from aux import nifti_write_like
    from shutil import copyfile
    
    sys.stdout.write('   Parsing input... ');
    
    fid = open((basenameOut + '.json'));
    dwiInfo=json.load(fid);
    fid.close();

    if (dwi[-3:]=='.gz'):
        basename    = os.path.basename(dwi[0:-7]);
    else:
        basename    = os.path.basename(dwi[0:-4]);
         
    basenameInp = os.path.dirname(dwi) + '/' + basename;

    bval = np.loadtxt((basenameInp + '.bval'));
    bvec = np.loadtxt((basenameInp + '.bvec'));

    RL_dwis = [];
    LR_dwis = [];    
    PA_dwis = [];
    AP_dwis = [];
    IS_dwis = [];
    SI_dwis = [];

    if (dwiInfo['phase encoding of volumes']== 'is not same for all volumes'):

        nii = nib.load(dwi);
        img = nii.get_data();

        inds_RL = [];
        inds_LR = [];
        inds_PA = [];        
        inds_AP = [];
        inds_IS = [];
        inds_SI = [];
        
        for i in range(0,dwiInfo['number of volumes']):
            
            peDir=dwiInfo['phase encoding directions']['volume ' + str(i+1)];
            
            if (peDir=='i'):
                inds_RL.append(i);
            if (peDir=='i-'):
                inds_LR.append(i);
            if (peDir=='j'):
                inds_PA.append(i);
            if (peDir=='j-'):
                inds_AP.append(i);
            if (peDir=='k'):
                inds_IS.append(i);
            if (peDir=='k-'):
                inds_SI.append(i);
        
        if (len(inds_RL)>0):
            img_RL = img[:,:,:,inds_RL];
            nifti_write_like(img_RL,nii,(basenameOut+ '_RL.nii.gz'));
            np.savetxt((basenameOut+ '_RL.bval'), np.array(bval[inds_RL],int),     delimiter='',  fmt='%d',    newline=' ');
            np.savetxt((basenameOut+ '_RL.bvec'), np.array(bvec[:,inds_RL],float), delimiter=' ', fmt='%1.6f', newline='\n');
            RL_dwis.append((basenameOut+ '_RL.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_RL'),'i',len(inds_RL));
        if (len(inds_LR)>0):
            img_LR = img[:,:,:,inds_LR];
            nifti_write_like(img_LR,nii,(basenameOut+ '_LR.nii.gz'));
            np.savetxt((basenameOut+ '_LR.bval'), np.array(bval[inds_LR],int),     delimiter='',  fmt='%d',    newline=' ');
            np.savetxt((basenameOut+ '_LR.bvec'), np.array(bvec[:,inds_LR],float), delimiter=' ', fmt='%1.6f', newline='\n');
            LR_dwis.append((basenameOut+ '_LR.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_LR'),'i-',len(inds_LR));
        if (len(inds_PA)>0):
            img_PA = img[:,:,:,inds_PA];
            nifti_write_like(img_PA,nii,(basenameOut+ '_PA.nii.gz'));            
            np.savetxt((basenameOut+ '_PA.bval'), np.array(bval[inds_PA],int),     delimiter='',  fmt='%d',    newline=' ');
            np.savetxt((basenameOut+ '_PA.bvec'), np.array(bvec[:,inds_PA],float), delimiter=' ', fmt='%1.6f', newline='\n');
            PA_dwis.append((basenameOut+ '_PA.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_PA'),'j',len(inds_PA));
        if (len(inds_AP)>0):
            img_AP = img[:,:,:,inds_AP];
            nifti_write_like(img_AP,nii,(basenameOut+ '_AP.nii.gz'));
            np.savetxt((basenameOut+ '_AP.bval'), np.array(bval[inds_AP],int),     delimiter='',  fmt='%d',    newline=' ');
            np.savetxt((basenameOut+ '_AP.bvec'), np.array(bvec[:,inds_AP],float), delimiter=' ', fmt='%1.6f', newline='\n');
            AP_dwis.append((basenameOut+ '_AP.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_AP'),'j-',len(inds_AP));
        if (len(inds_IS)>0):
            img_IS = img[:,:,:,inds_IS];
            nifti_write_like(img_IS,nii,(basenameOut+ '_IS.nii.gz'));
            np.savetxt((basenameOut+ '_IS.bval'), np.array(bval[inds_IS],int),     delimiter='',  fmt='%d',    newline=' ');
            np.savetxt((basenameOut+ '_IS.bvec'), np.array(bvec[:,inds_IS],float), delimiter=' ', fmt='%1.6f', newline='\n');
            IS_dwis.append((basenameOut+ '_IS.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_IS'),'k',len(inds_IS));
        if (len(inds_SI)>0):
            img_SI = img[:,:,:,inds_SI];
            nifti_write_like(img_SI,nii,(basenameOut+ '_SI.nii.gz'));
            np.savetxt((basenameOut+ '_SI.bval'), np.array(bval[inds_SI],int),     delimiter='',  fmt='%d',    newline=' ');
            np.savetxt((basenameOut+ '_SI.bvec'), np.array(bvec[:,inds_SI],float), delimiter=' ', fmt='%1.6f', newline='\n');
            IS_dwis.append((basenameOut+ '_SI.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_SI'),'k-',len(inds_SI));
    
    else:
        
        peDir=dwiInfo['PhaseEncodingDirection'];
        if (peDir=='i'):
            copyfile(dwi,(basenameOut+ '_RL.nii.gz'));
            copyfile((basenameInp + '.bval'),(basenameOut+ '_RL.bval'));
            copyfile((basenameInp + '.bvec'),(basenameOut+ '_RL.bvec'));
            RL_dwis.append((basenameOut+ '_RL.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_RL'),'i',[]);
        if (peDir=='i-'):
            copyfile(dwi,(basenameOut+ '_LR.nii.gz'));
            copyfile((basenameInp + '.bval'),(basenameOut+ '_LR.bval'));
            copyfile((basenameInp + '.bvec'),(basenameOut+ '_LR.bvec'));
            LR_dwis.append((basenameOut+ '_LR.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_LR'),'i-',[]);
        if (peDir=='j'):
            copyfile(dwi,(basenameOut+ '_PA.nii.gz'));
            copyfile((basenameInp + '.bval'),(basenameOut+ '_PA.bval'));
            copyfile((basenameInp + '.bvec'),(basenameOut+ '_PA.bvec'));
            PA_dwis.append((basenameOut+ '_PA.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_PA'),'j',[]);
        if (peDir=='j-'):
            copyfile(dwi,(basenameOut+ '_AP.nii.gz'));
            copyfile((basenameInp + '.bval'),(basenameOut+ '_AP.bval'));
            copyfile((basenameInp + '.bvec'),(basenameOut+ '_AP.bvec'));
            AP_dwis.append((basenameOut+ '_AP.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_AP'),'j-',[]);
        if (peDir=='k'):
            copyfile(dwi,(basenameOut+ '_IS.nii.gz'));
            copyfile((basenameInp + '.bval'),(basenameOut+ '_IS.bval'));
            copyfile((basenameInp + '.bvec'),(basenameOut+ '_IS.bvec'));
            IS_dwis.append((basenameOut+ '_IS.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_IS'),'k',[]);
        if (peDir=='k-'):
            copyfile(dwi,(basenameOut+ '_SI.nii.gz'));
            copyfile((basenameInp + '.bval'),(basenameOut+ '_SI.bval'));
            copyfile((basenameInp + '.bvec'),(basenameOut+ '_SI.bvec'));
            SI_dwis.append((basenameOut+ '_SI.nii.gz'));
            copy_json(dwi,(basenameOut + '.json'),(basenameOut + '_SI'),'k-',[]);
            
    sys.stdout.write('DONE \n');
        
    return (RL_dwis,LR_dwis,PA_dwis,AP_dwis,IS_dwis,SI_dwis);
    