#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun  9 09:31:42 2020

@author: baran
"""

def phaseWrapper(prepEnv,T1path,outputPath,up,dn):

   from aux import nifti_extract_a_b0
   import subprocess
   import os
   import sys
   import json

   if not os.path.exists(outputPath + '/synb0'): os.mkdir(outputPath + '/synb0')
   sys.stdout.write('Synthesizing a b0 image from ' + up + ' phase encoded image ... ');
   nifti_extract_a_b0((outputPath + '/' + up + '.nii.gz'),(outputPath + '/' + up),(outputPath + '/synb0/' + up + '_b0'),50)
   subprocess.call(['sbatch', '--wait', 'pipeline_withCustomPaths_Part1.sh', (outputPath + '/synb0/' + up + '_b0.nii.gz'), T1path, (outputPath + '/synb0')], env=prepEnv);
   subprocess.call(['sbatch', '--wait', 'pipeline_withCustomPaths_Part2.sh', (outputPath + '/synb0/' + up + '_b0.nii.gz'), T1path, (outputPath + '/synb0')], env=prepEnv);
   subprocess.call(['cp', (outputPath + '/synb0/b0_u.nii.gz'),         (outputPath + '/' + dn + '.nii.gz')], env=prepEnv);
   subprocess.call(['cp', (outputPath + '/synb0/' + up + '_b0.bval'),  (outputPath + '/' + dn + '.bval')],   env=prepEnv);
   subprocess.call(['cp', (outputPath + '/synb0/' + up + '_b0.bvec'),  (outputPath + '/' + dn + '.bvec')],   env=prepEnv);

   # Write a json file with opposite phase encoding with total readout time of 10ms (eddy doesn't accept anything below this value)
   fid = open((outputPath + '/' + up + '.json'));
   dwiInfo=json.load(fid);
   fid.close();

   report = open((outputPath + '/' + dn + '.json'),'w');    
   report.write('{\n');
   report.write('"generated by": "dwiprep -> parseInput -> synb0Functions"');
   report.write(',\n"input": "'  + outputPath  + '/' + up + '"');    
   report.write(',\n"output": "' + outputPath  + '/' + dn + '"');

   report.write(',\n"dcmmeta_shape": '                 + str(dwiInfo['dcmmeta_shape']));
   report.write(',\n"number of volumes": '             + str(1));
  
   report.write(',\n"PartialFourier": '                + str(float(dwiInfo['PartialFourier'])));
   report.write(',\n"TotalReadoutTime": '              + str(0.01));
    
   report.write(',\n"MultibandAccelerationFactor": '   + str(dwiInfo['MultibandAccelerationFactor']));
    
   try:
       sliceTimings = dwiInfo['global']['slices']['CsaImage.TimeAfterStart'][0:dwiInfo['dcmmeta_shape'][2]];
       report.write(',\n"global":{');
       report.write('\n"slices":{');
       report.write('\n"CsaImage.TimeAfterStart": '+str(sliceTimings));
       report.write('\n}');
       report.write('\n}');
   except:
       sys.stdout.write('');
    
    
   peDir=dwiInfo['PhaseEncodingDirection'];
   if (peDir=='i'):  report.write(',\n"PhaseEncodingDirection": "i-"');
   if (peDir=='i-'): report.write(',\n"PhaseEncodingDirection": "i"');
   if (peDir=='j'):  report.write(',\n"PhaseEncodingDirection": "j-"');
   if (peDir=='j-'): report.write(',\n"PhaseEncodingDirection": "j"');
   if (peDir=='k'):  report.write(',\n"PhaseEncodingDirection": "k-"');
   if (peDir=='k-'): report.write(',\n"PhaseEncodingDirection": "k"');

        
   report.write(',\n"result": "SUCCESS"');
   report.write('\n}');
   report.close();

def synb0ifneeded(prepEnv,T1path,RL_dwis,LR_dwis,PA_dwis,AP_dwis,IS_dwis,SI_dwis,outputPath):

   if ( (RL_dwis!=[]) & (LR_dwis==[]) ) : 
      phaseWrapper(prepEnv,T1path,outputPath,'RL','LR')
      LR_dwis.append((outputPath + '/LR.nii.gz'))

   if ( (LR_dwis!=[]) & (RL_dwis==[]) ) : 
      phaseWrapper(prepEnv,T1path,outputPath,'LR','RL')
      RL_dwis.append((outputPath + '/RL.nii.gz'))

   if ( (AP_dwis!=[]) & (PA_dwis==[]) ) : 
      phaseWrapper(prepEnv,T1path,outputPath,'AP','PA')
      PA_dwis.append((outputPath + '/PA.nii.gz'))

   if ( (PA_dwis!=[]) & (AP_dwis==[]) ) : 
      phaseWrapper(prepEnv,T1path,outputPath,'PA','AP')
      AP_dwis.append((outputPath + '/AP.nii.gz'))

   if ( (IS_dwis!=[]) & (SI_dwis==[]) ) : 
      phaseWrapper(prepEnv,T1path,outputPath,'IS','SI')
      SI_dwis.append((outputPath + '/SI.nii.gz'))

   if ( (SI_dwis!=[]) & (IS_dwis==[]) ) : 
      phaseWrapper(prepEnv,T1path,outputPath,'SI','IS')
      IS_dwis.append((outputPath + '/IS.nii.gz'))

   return (RL_dwis,LR_dwis,PA_dwis,AP_dwis,IS_dwis,SI_dwis)




