#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  5 09:31:42 2018

@author: baran
"""

# Verify input
def run_verifyInput(dwi,basenameOut,reference_report):
    
    import os
    import sys
    import nibabel as nib
    import numpy as np
    import json
    
    refInfo=[];
    if reference_report:
        fid = open(reference_report);
        refInfo=json.load(fid);
        fid.close();    
    
    report      = open((basenameOut + '.json'),'w');
    report.write('{\n');
    report.write('"generated by": "dwiprep -> verifyInput -> run_verifyInput"');
    report.write(',\n"input": "' + dwi + '"');
    report.write(',\n"output": "' + basenameOut + '.json"');    
    
    sys.stdout.write('   Verifying input... ');
    
    if (dwi[-3:]=='.gz'):
        basename    = os.path.basename(dwi[0:-7]);
    else:
        basename    = os.path.basename(dwi[0:-4]);
         
    basenameInp = os.path.dirname(dwi) + '/' + basename;
    
    nii         = nib.load(dwi);
    ndim        = len(nii.shape);
    
    if (ndim==4):
        nv      = nii.shape[3];
    elif (ndim==3):
        nv      = 1;
    else:
        report.write(',\n"image dimension": "' + str(ndim) + '"');
        report.write((',\n"result": "FAILED, input dimension cannot be '+ str(ndim) +'"' ));
        report.write('\n}');
        report.close();
        sys.exit('input dimension cannot be ' + str(ndim) + ' :' + dwi);

    report.write(',\n"dcmmeta_shape": [' + str(nii.shape[0]) + ', ' + str(nii.shape[1]) + ', ' + str(nii.shape[2]) + ']');
    report.write(',\n"number of volumes": ' +str(nv));
        
    
    bval        = np.atleast_1d(np.loadtxt((basenameInp + '.bval')));
    
    if (bval.shape[0]!=nv):
        report.write(',\n"bval count": "' + str(bval.shape[0]) + '"');
        report.write(',\n"result": "FAILED, bval count does not match number of volumes"');
        report.write('\n}');
        report.close();
        sys.exit('bval count does not match number of volumes');
    
    bvec        = np.atleast_2d(np.loadtxt((basenameInp + '.bvec')));
    
    if (bvec.shape[0]==1):
        bvec=bvec.transpose();
    
    if (bvec.shape[0]!=3):
        report.write(',\n"bvec row count": "'+str(bvec.shape[0])+'"');
        report.write(',\n"result": "FAILED, bvec row count is not 3"');
        report.write('\n}');
        report.close();
        sys.exit('bvec row count is not 3');
        
    if (bvec.shape[1]!=nv):
        report.write(',\n"bvec column count": "'+str(bvec.shape[1])+'"');
        report.write(',\n"result": "FAILED, bvec column count does not match number of volumes"');
        report.write('\n}');
        report.close();
        sys.exit('bvec column count does not match number of volumes');

    fid = open((basenameInp + '.json'));
    dwiInfo=json.load(fid);
    fid.close();
    
    
    # Verify PartialFourier which is needed for Gibbs artefact removal
    try:
        PartialFourier = float(dwiInfo['PartialFourier']);
        report.write(',\n"PartialFourier": ' +str(PartialFourier));
    except:            
        report.write(',\n"result": "FAILED, PartialFourier missing or wrong ' + (basenameInp + '.json') + '"');
        report.write('\n}');
        report.close();
        sys.exit('missing PartialFourier in ' + (basenameInp + '.json'))

#    THIS MIGHT NOT BE NEEDED        
#    if refInfo : 
#        PartialFourier_ref = float(refInfo['PartialFourier']);
#        if (PartialFourier!=PartialFourier_ref):
#            report.write(',\n"result": "FAILED, PartialFourier is not same as other images ' + (basenameInp + '.json') + '"');
#            report.write('\n}');
#            report.close();
#            sys.exit('PartialFourier in ' + basenameInp + ' does not match others'); 
    
#    try:
#        aqAxes=dwiInfo['ImageOrientationPatientDICOM'];
#        if ((aqAxes[0]==0) & (aqAxes[1]==0) & (aqAxes[2]==0)) | ((aqAxes[3]==0) & (aqAxes[4]==0) & (aqAxes[5]==0)) :
#            raise;
#        report.write(',\n"ImageOrientationPatientDICOM": ' +str(aqAxes));
#    except:            
#        report.write(',\n"result": "FAILED, ImageOrientationPatientDICOM missing or wrong ' + (basenameInp + '.json') + '"');
#        report.write('\n}');
#        report.close();
#        sys.exit('missing ImageOrientationPatientDICOM in ' + (basenameInp + '.json'));
#        
#    if refInfo : 
#        aqAxes_ref = refInfo['ImageOrientationPatientDICOM'];
#        if (aqAxes!=aqAxes_ref):
#            report.write(',\n"result": "FAILED, ImageOrientationPatientDICOM is not same as other images ' + (basenameInp + '.json') + '"');
#            report.write('\n}');
#            report.close();
#            sys.exit('ImageOrientationPatientDICOM in ' + basenameInp + ' does not match others');

    # Verify TotalReadoutTime which is needed for topup/eddy
    try:
        TotalReadoutTime = float(dwiInfo['TotalReadoutTime']);
        report.write(',\n"TotalReadoutTime": ' +str(TotalReadoutTime));
    except:
        report.write(',\n"result": "FAILED, TotalReadoutTime missing or wrong ' + (basenameInp + '.json') + '"');
        report.write('\n}');
        report.close();
        sys.exit('missing TotalReadoutTime in ' + (basenameInp + '.json'));
    
    if refInfo : 
        TotalReadoutTime_ref = float(refInfo['TotalReadoutTime']);
        if (TotalReadoutTime!=TotalReadoutTime_ref):
            report.write(',\n"result": "FAILED, TotalReadoutTime is not same as other images ' + (basenameInp + '.json') + '"');
            report.write('\n}');
            report.close();
            sys.exit('TotalReadoutTime in ' + basenameInp + ' does not match others');
    
    # Verify MultibandAccelerationFactor which is needed for topup/eddy
    try:
        MultibandAccelerationFactor = dwiInfo['MultibandAccelerationFactor'];
        report.write(',\n"MultibandAccelerationFactor": ' +str(MultibandAccelerationFactor));
    except:
        report.write(',\n"MultibandAccelerationFactor": 1');
        sys.stdout.write(('Setting MultibandAccelerationFactor to default=1 since it is missing in' + basenameInp + '.json'));
    
    # Verify slice timings which is needed for topup/eddy
    try:
        sliceTimings = dwiInfo['global']['slices']['CsaImage.TimeAfterStart'][0:nii.shape[2]];
        report.write(',\n"global":{');
        report.write('\n"slices":{');
        report.write('\n"CsaImage.TimeAfterStart": '+str(sliceTimings));
        report.write('\n}');
        report.write('\n}');
    except:
        sys.stdout.write('');
    
    
    
    # Verify PhaseEncodingDirection which is needed for topup/eddy
    try:
        phaseEncodingInfo=dwiInfo['PhaseEncodingDirection'];
    except:
        try:
            phaseEncodingInfo=dwiInfo['PhaseEncodingAxis'];
        except:
            report.write(',\n"result": "FAILED, missing PhaseEncodingDirection in ' + (basenameInp + '.json') + '"');
            report.write('\n}');
            report.close();
            sys.exit('missing PhaseEncodingDirection in ' + (basenameInp + '.json'));
    
    phaseEncoder=np.zeros(nv,dtype=int)
    if not phaseEncodingInfo:        
        report.write(',\n"phase encoding of volumes": "is not same for all volumes"');
        report.write(',\n"PhaseEncodingDirection": " "');
        report.write(',\n"phase encoding directions": { \n');
        for n in range(0, nv):
            if n<9:
                try:
                    pe=dwiInfo['PhaseEncodingDirection_00'+str(n+1)];
                except:
                    report.write('\n}'); 
                    report.write(',\n"result": "FAILED, missing PhaseEncodingDirection_00' + str(n+1) + ' in ' + (basenameInp + '.json') + '"');
                    report.write('\n}');
                    report.close();
                    sys.exit('missing PhaseEncodingDirection_00' + str(n+1) + ' in ' + (basenameInp + '.json'));
            elif n<99:
                try:
                    pe=dwiInfo['PhaseEncodingDirection_0'+str(n+1)];
                except:
                    report.write('\n}');
                    report.write(',\n"result": "FAILED, missing PhaseEncodingDirection_0' + str(n+1) + ' in ' + (basenameInp + '.json') + '"');
                    report.write('\n}');
                    report.close();
                    sys.exit('missing PhaseEncodingDirection_0' + str(n+1) + ' in ' + (basenameInp + '.json'));
            else:
                try:
                    pe=dwiInfo['PhaseEncodingDirection_'+str(n+1)];
                except:
                    report.write('\n}');
                    report.write(',\n"result": "FAILED, missing PhaseEncodingDirection_' + str(n+1) + ' in ' + (basenameInp + '.json') + '"');
                    report.write('\n}');
                    report.close();
                    sys.exit('missing PhaseEncodingDirection_' + str(n+1) + ' in ' + (basenameInp + '.json'));
            
            if (n==0):
                report.write('"volume '+str(n+1)+'": "'+pe+'"');
            else:
                report.write(',\n"volume '+str(n+1)+'": "'+pe+'"');
                
            if (pe=='i'):
                phaseEncoder[n]= 1;
            elif (pe=='i-'):
                phaseEncoder[n]=-1;
            elif (pe=='j'):
                phaseEncoder[n]= 2;
            elif (pe=='j-'):
                phaseEncoder[n]=-2;
            elif (pe=='k'):
                phaseEncoder[n]= 3;
            elif (pe=='k-'):
                phaseEncoder[n]=-3;
            else:
                report.write('\n}'); 
                report.write(',\n"result": "FAILED, unknown PhaseEncodingDirection for volume ' + str(n+1)+ ': ' + pe + ', please fix ' + (basenameInp + '.json') + '"');
                report.write('\n}');
                report.close();
                sys.exit('unknown PhaseEncodingDirection for volume ' + str(n+1)+ ': ' + pe + '"');
        report.write('\n}'); 
    else:        
        pe=phaseEncodingInfo;
        report.write(',\n"phase encoding of volumes": "is same for all"');
        report.write(',\n"PhaseEncodingDirection": "'+pe+'"');
#        report.write(',\n"phase encoding directions": "'+pe+'"');
        
        doubleDef=False;
        try:
            dwiInfo['PhaseEncodingDirection_001'];
            report.write(',\n"result": "FAILED, PhaseEncodingDirection and PhaseEncodingDirection_001 cannot be defined together"');
            report.write('\n}');
            report.close();
            doubleDef=True;
        except:
            pass;
            
        if (doubleDef==True):
            sys.exit('PhaseEncodingDirection and PhaseEncodingDirection_001 cannot be defined together');
        
        if (pe=='i'):
            phaseEncoder= phaseEncoder+1;
        elif (pe=='i-'):
            phaseEncoder= phaseEncoder-1;
        elif (pe=='j'):
            phaseEncoder= phaseEncoder+2;
        elif (pe=='j-'):
            phaseEncoder= phaseEncoder-2;
        elif (pe=='k'):
            phaseEncoder= phaseEncoder+3;
        elif (pe=='k-'):
            phaseEncoder= phaseEncoder-3;
        else:
            report.write(',\n"result": "FAILED, unknown PhaseEncodingDirection: ' + pe + ', please fix ' + (basenameInp + '.json') + '"');
            report.write('\n}');
            report.close();
            sys.exit('unknown PhaseEncodingDirection: ' + pe + '"');


    report.write(',\n"result": "SUCCESS"');
    report.write('\n}');
    report.close();
    
    sys.stdout.write('DONE \n');
    
    return;
    
#    return (dwi,dwiInfo,bval,bvec,phaseEncoder);
